# EMBEDDED SERVER CONFIGURATION
server:
    port: ${port:8098}
    context-path: /
    error.whitelabel.enabled: false
    compression:
      enabled: true
      min-response-size: 1024
      mime-types:
          - text/html
          - text/css
          - text/plain
          - text/xml
          - application/json
          - application/javascript
# JACKSON
spring:
    jackson.serialization:
        write_dates_as_timestamps: false
        

        
# EUREKA
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
# Disable spring basic authentication security
security:
  basic:
    enabled: false
  oath2:
    resource:
        userInfoUri: http://localhost:8083/uaa/user
# LOGGING
#logging.level.org.springframework.security: DEBUG

---

spring:
  profiles: docker

# EUREKA
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8091/eureka/
 
   



---

spring:
  profiles: standalone

# EUREKA
eureka:
  instance:
    hostname: localhost
    port: 8091
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
